## Spring DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)
spring:
  # The SQL dialect makes Hibernate generate better SQL for the chosen database
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
        jdbc:
          lob:
            non_contextual_creation: true
        #dialect: org.hibernate.dialect.PostgreSQL9Dialect
    hibernate:
      # Hibernate ddl auto (create, create-drop, validate, update)
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/arquivei-test-db
    username: postgres
    password: Postgres2019!


use_jdbc_metadata_defaults: false
non_contextual_creation: true